image: python:3.6

stages:
  - test
  - deploy

before_script:
  - pip install wheel

test_job:
  stage: test
  script:
    - pip install pytest
    - python setup.py test

deploy_job:
  stage: deploy
  only:
    - tags
  script:
    - pip install twine
    - python -m twine upload -u cimba -p $TWINE_PASSWORD dist/*.whl
