image: python:3.6

stages:
  - test
  - deploy

before_scirpt:
  - pip install wheel
  - python setup.py bdist_wheel

test_job:
  stage: test
  script:
    - pip install pytest
    - pytest

deploy_job:
  stage: deploy
  only:
    - master
    - tags
  script:
    - pip install twine
    - python -m twine upload -u cimba -p $TWINE_PASSWORD dist/*.whl
